name: Release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Restore
      run: dotnet restore -v m
    - name: Build
      run: dotnet build --configuration Release --no-restore -v m
    - name: Test
      run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Codecoverage
      uses: codecov/codecov-action@v1.0.13
      with:
        fail_ci_if_error: true
    - name: Sonarcloud
      uses: spoland/dotnet-sonarcloud-analysis@v1.0
      with:
        project-key: frankhaugen_Frank.Libraries
        sonar-host-url: https://sonarcloud.io
        sonar-organization: frankhaugen
        opencover-reports-paths: "**/*.opencover.xml"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Pack NuGet
      run: dotnet pack --no-build --no-restore -v m --output nupkgs -p:PackageVersion=1.$GITHUB_RUN_NUMBER
    - name: Push Primary NuGet
      run: dotnet nuget push **/Frank.Libraries.All.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push AutoFixture NuGet
      run: dotnet nuget push **/Frank.Libraries.AutoFixture.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push Extensions NuGet
      run: dotnet nuget push **/Frank.Libraries.Extensions.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push Enum NuGet
      run: dotnet nuget push **/Frank.Libraries.Enums.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push Json NuGet
      run: dotnet nuget push **/Frank.Libraries.Json.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push MongoDb NuGet
      run: dotnet nuget push **/Frank.Libraries.MongoDb.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push Logging NuGet
      run: dotnet nuget push **/Frank.Libraries.Logging.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push Constants NuGet
      run: dotnet nuget push **/Frank.Libraries.Constants.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push Brreg NuGet
      run: dotnet nuget push **/Frank.Libraries.Brreg.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push XML NuGet
      run: dotnet nuget push **/Frank.Libraries.Xml.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
    - name: Push Security NuGet
      run: dotnet nuget push **/Frank.Libraries.Security.1.$GITHUB_RUN_NUMBER.0.nupkg -k ${{ secrets.NugetKey }} -s https://api.nuget.org/v3/index.json
